#!/usr/bin/env python3
"""
Rebuild a file from chunk manifest JSON and validate SHA-256 integrity.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def sha256_file(path: Path, buf_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            b = f.read(buf_size)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def rebuild_from_manifest(manifest_path: Path, output_path: Path | None = None) -> Path:
    if not manifest_path.is_file():
        raise FileNotFoundError(f"manifest not found: {manifest_path}")

    with manifest_path.open("r", encoding="utf-8") as f:
        manifest = json.load(f)

    chunks = manifest.get("chunks")
    if not isinstance(chunks, list) or not chunks:
        raise ValueError("manifest chunks missing or invalid")

    original_name = manifest.get("original_file_name")
    if not isinstance(original_name, str) or not original_name:
        raise ValueError("manifest original_file_name missing")

    expected_sha = manifest.get("original_sha256")
    if not isinstance(expected_sha, str) or len(expected_sha) != 64:
        raise ValueError("manifest original_sha256 missing or invalid")

    expected_size = manifest.get("original_size")
    if not isinstance(expected_size, int) or expected_size < 0:
        raise ValueError("manifest original_size missing or invalid")

    sorted_chunks = sorted(chunks, key=lambda c: int(c["index"]))
    chunk_dir = manifest_path.parent

    if output_path is None:
        output_path = chunk_dir / original_name
    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    total_written = 0
    with output_path.open("wb") as out:
        for c in sorted_chunks:
            chunk_file = c.get("file")
            chunk_size = c.get("size")
            chunk_sha = c.get("sha256")
            if not isinstance(chunk_file, str):
                raise ValueError("chunk file missing/invalid")
            if not isinstance(chunk_size, int) or chunk_size < 0:
                raise ValueError(f"chunk size invalid for {chunk_file}")
            if not isinstance(chunk_sha, str) or len(chunk_sha) != 64:
                raise ValueError(f"chunk sha256 invalid for {chunk_file}")

            chunk_path = (chunk_dir / chunk_file).resolve()
            if not chunk_path.is_file():
                raise FileNotFoundError(f"missing chunk: {chunk_path}")

            data = chunk_path.read_bytes()
            if len(data) != chunk_size:
                raise ValueError(
                    f"chunk size mismatch for {chunk_file}: "
                    f"expected {chunk_size}, got {len(data)}"
                )
            got_chunk_sha = sha256_bytes(data)
            if got_chunk_sha != chunk_sha:
                raise ValueError(
                    f"chunk hash mismatch for {chunk_file}: "
                    f"expected {chunk_sha}, got {got_chunk_sha}"
                )

            out.write(data)
            total_written += len(data)

    if total_written != expected_size:
        raise ValueError(
            f"reconstructed size mismatch: expected {expected_size}, got {total_written}"
        )

    got_sha = sha256_file(output_path)
    if got_sha != expected_sha:
        raise ValueError(
            f"integrity check failed: expected {expected_sha}, got {got_sha}"
        )

    return output_path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Rebuild original file from chunk manifest and verify integrity."
    )
    parser.add_argument("manifest", help="Path to master JSON generated by compressor.py")
    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output file path (default: original filename in manifest directory)",
    )
    args = parser.parse_args()

    manifest_path = Path(args.manifest).expanduser().resolve()
    output = Path(args.output).expanduser().resolve() if args.output else None
    rebuilt = rebuild_from_manifest(manifest_path, output)
    print(f"rebuilt file: {rebuilt}")
    print("integrity check: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
